name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build-release-binaries:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Build Time
        run:  echo BUILD_TIME=$(date -u +%Y%m%d%H%M) >> ${GITHUB_ENV}
      - name: Build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
          sha256sum: true
          md5sum: false
          asset_name: ${BINARY_NAME}-${{ env.BUILD_TIME }}-${{ matrix.goos }}-${{ matrix.goarch }}
          compress_assets: false
